### ISSUE TITLE
Usage is a bit verbose

### ISSUE THREAD

**Issue by arichiardi** [abiocljs/abio-node#3]
Hi folks, I think my question is more like an api/public interface question and I apologise if this has already been  :smile: 

I have a question about usability, I am finding myself writing:

```clojure
(defn directory? [directory-path]
  (try
    (io/-directory? *io-bindings* directory-path)
    (catch js/Error e
      false)))
```

The `*io-bindings*` there feels a bit unnatural as I actually thought that

```clojure
(abio.core/set-bindings! (node/bindings))
```

would actually set a global that all the function would read from. It makes sense to me to set a global from where everything reads from, not something I need to pass around again but I understand this is maybe due to the async nature of JavaScript.

Is there anything we can do to improve things?

/cc @ElChache

**Comment by mfikes** [comment]
@arichiardi Hrm. Is the function you are looking for already over here? https://github.com/abiocljs/abio/blob/master/src/abio/io.cljs#L186-L189

**Comment by arichiardi** [comment]
Oh, maybe I misread that one! I was checking the walkthrough and I thought I had to use it that way. Closing and sorry for the noise.
